feat: Support for .well-known method of Certbot renewal

diff --git a/cb-renew b/cb-renew
--- a/cb-renew
+++ b/cb-renew
@@ -15,9 +15,10 @@ Unlike the regular \"certbot renew\" process this script has the following behav
 
 
 -m [method]         Specify the Certbot setup mode
-			\"auto\"  - Try to detect the the method automatically (default)
-                        \"dme\"   - DNS-Made-Easy DNS auth
-			\"nginx\" - Full server renew via Nginx service start / setop
+			\"auto\"     - Try to detect the the method automatically (default)
+			\"dme\"      - DNS-Made-Easy DNS auth (uses LE: DME method)
+			\"nginx\"    - Full server renew via Nginx service start / stop (uses LE: standalone method)
+			\"nginx-wr\" - Use Nginx + Webroot (via /var/www) (uses LE: webroot method)
 
 -h, --help          Show command line help
 "
@@ -71,8 +72,13 @@ if [ "$METHOD" == "auto" ]; then
 		echo "Found DME config file - assuming 'DNS Made Easy' method"
 		METHOD="dme"
 	elif [ `ps ax | grep -q nginx; echo "$?"` == 0 ]; then
-		echo "Found Nginx process - assuming 'Nginx' method"
-		METHOD='nginx'
+		if [ `grep -q .well-known /etc/nginx/nginx.conf; echo "$?"` == 0 ]; then
+			echo "Found Nginx process + .well-known in nginx.conf file - assuming 'Nginx-WR' method"
+			METHOD='nginx'
+		else
+			echo "Found Nginx process - assuming 'Nginx' method"
+			METHOD='nginx'
+		fi
 	else
 		echo "Cannot automatically determine method to use - aborting"
 		exit 1
@@ -98,17 +104,39 @@ fi
 if [ "$METHOD" == 'nginx' ]; then
 	echo "Stopping Nginx process..."
 	sudo service nginx stop
+elif [ "$METHOD" == 'nginx-wr' ]; then
+	echo "Creating /var/www/.well-known..."
+	if [ -e "/var/www/.well-known" ]; then
+		echo "ERROR: /var/www/.well-known already exists, remove it to continue"
+		exit 1
+	fi
+	sudo mkdir /var/www/.well-known
 fi
 # }}}
 
 # 2. Renewal {{{
-sudo $CERTBOT renew
+if [ "$METHOD" == 'nginx' ]; then
+	echo "Renewing via standalone..."
+	sudo $CERTBOT renew --standalone
+elif [ "$METHOD" == 'nginx-wr' ]; then
+	echo "Renewing via webroot..."
+	sudo $CERTBOT renew --webroot
+elif [ "$METHOD" == 'dme' ]; then
+	echo "Renewing via DME..."
+	sudo $CERTBOT renew
+fi
 # }}}
 
 # 3. Post-processing steps {{{
 if [ "$METHOD" == 'nginx' ]; then
 	echo "Starting Nginx process..."
 	sudo service nginx start
+elif [ "$METHOD" == 'nginx-wr' ]; then
+	echo "Cleaning up /var/www/.well-known..."
+	sudo rm -r /var/www/.well-known
+
+	echo "Reloading Nginx process..."
+	sudo service nginx reload
 elif [ "$METHOD" == "dme" ]; then
 	echo "Reloading Nginx certificate data..."
 	sudo service nginx reload
